apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kubernetes
  labels:
    app: hello-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kubernetes
  template:
    metadata:
      labels:
        app: hello-kubernetes
    spec:
      containers:
        - name: hello-kubernetes
          image: upkar/myapp:latest
          ports:
          - containerPort: 8080
          env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: my-config
                key: my.properties
          - name: API_CREDS
            valueFrom:
              secretKeyRef:
                name: api-creds
                key: key
          volumeMounts:
          - name: api-creds
            mountPath: "/etc/api"
            readOnly: true
      volumes:
      - name: api-creds
        secret:
          secretName: api-creds

